### ISSUE TITLE
configure: error: Could not link against boost_filesystem ! on ppc64le 

### ISSUE THREAD

**Issue by grubles** [Blockstream/liquid#18]
### Describe the issue
`./configure` fails with error: `configure: error: Could not link against boost_filesystem !`. 
### Can you reliably reproduce the issue?
Yes.
#### If so, please list the steps to reproduce below:
1. `./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"`

### Actual behaviour
Tell us what happens instead
```
checking for boostlib >= 1.47.0... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::Program_Options library is available... yes
configure: error: Could not link against boost_filesystem !
```

### What version of bitcoin-core are you using?
Self compiled 0.17.1 Core, which builds successfully. 

### Machine specs:
- OS: Ubuntu 18.04 (ppc64le) 
- CPU: Power9 
- RAM: n/a
- Disk size: n/a
- Disk Type (HD/SDD): n/a

**Comment by instagibbs** [comment]
yay boost. You try a depends build?

**Comment by instagibbs** [comment]
see: https://github.com/Blockstream/liquid/tree/liquid.3.14.1/depends

**Comment by grubles** [comment]
I'll give it a shot and report back.

**Comment by grubles** [comment]
I think we can close this now. Elements 0.17.01 builds successfully.
