### ISSUE TITLE
"sendmany" shows "insufficient funds", but it's not true

### ISSUE THREAD

**Issue by devfans** [Blockstream/liquid#21]
Got error -6 when calling `sendmany` for several times.
```e-cli sendmany "" "{\"address\": 0.000336}" 1 ""```

```
error code: -6
error message:
Account has insufficient funds
```

But `getwalletinfo` shows me I absolutely have enough bitcoin balance.

Not sure if it's an issue only with liquid or it's from bitcoin core.

I am running the first release of liquid daemon node and connected to latest bitcoind node.

**Comment by instagibbs** [comment]
How much funds do you have?

**Comment by devfans** [comment]
I have more than 0.2 in the wallet.

**Comment by instagibbs** [comment]
did you receive the funds using the "account" functionality?

If all your funds are in the default `""` account, you might have to hop on IRC/Slack for more debugging as this is unexpected.

**Comment by devfans** [comment]
Yes, it's in the default account, seems only `sendmany` got the issue while `sendtoaddress` is working well.

**Comment by instagibbs** [comment]
Is this in regtest or mainnet? We have pretty extensive tests so I'm trying
to see what I can do to nail this down.

**Comment by devfans** [comment]
It's in mainnet. Here's another example that threw the error: ```e-cli sendmany "" "{\"address1\": 0.000754,\"address2\": 0.000393,\
"address3\": 0.001040}" 1 "" "[\"address1\",\"address2\",\"address3\"]"
```
The balance in `getwalletinfo` was 0.25602663

**Comment by instagibbs** [comment]
@devfans wondering if we can take this "offline" so I can get more info? I'm "instagibbs" on freenode, or get on blockstream.slack.com, channel #elements

**Comment by devfans** [comment]
Sure, seems I dont have access to login blockstream's slack. Maybe need an invitation? I tried on freenode, but not sure if I successfully left a message to you.

**Comment by instagibbs** [comment]
I don't see it, you can also join freenode #sidechains-dev

**Comment by devfans** [comment]
Now since I know the possible reason(dusted account) of the issue, now closing it.

**Comment by dspicher** [comment]
I've had the exact same problem, without dust UTXOx, on Liquid's mainnet. Was there any conclusion as to what caused it?

**Comment by instagibbs** [comment]
It was dust. Not sure what issue you're having.
