### ISSUE TITLE
Claiming liquid peg-in: „The txoutproof must contain bitcoinTx and only bitcoinTX“

### ISSUE THREAD

**Issue by philipp634** [Blockstream/liquid#31]
I‘m trying to do a liquid pegin. Generated the pegin address and sent funds to it, waited < 102 blocks. When trying to claim them with

    liquid-cli claimpegin “rawtransaction“ “txoutproof“
The result is

    

        Error code: -8 
    Error message: The txoutproof must contain bitcoinTx and only bitcoinTX

The txoutproof was done on a -txindex enabled full node `gettxoutproof “[\“txid\“]“`

    00008020f2e6bcdb95b4bed4dfcd86f06a030f81dfe9a389fcc829000000000000000000906126d1d4b095843acb3f72c00f0d482cc6c85f2ca564b859975066936498e38482d55c38ff2917200bf44bde0a00000ce17736066f77aa7b82cc8eb388c58bba64b6eef0c356be9ee2edad21f89feedf2722bde65af8e4c768be1a8b00158c3689d572b839b8844186e0a4693c8e1bace06a92b0384c8b562cf202244de44d182a32e12367f832f23815025d7404771012579f301534ffa8b1c9ce720065fb07ec87ecac49917619d83f8cc78f52902e80bb37caf6d42a08b109d59538c6636c955fb682831766d9474a5b77f4bb7939903e08df4087f2096d463da09633c3cf23aa7fc76cc5315a6da9ef0a291f2c4e592314fb45377d7927b61a45c42ea964c533014bd7a1f3275780f74140ed937e8e516696ffe663e38889dc3ec0908f249a4292ee61931b5dec552fb16edb4dcb1d04c0ec0abe83d8a9f60de39a8c946a47010b0b73bdbef98d6845cc7f94feae824f697c755208d64b2ddbe9ddefbffde0617a97462d129a9cdd89b981ac0bc0a5d9f861b9e02db5918ddbc4382951c89c23bf59fb7ea8b2cc6a740ecd7af21534529cc91d163f73205244cc7fdaa04f0599de4ada39ceaba96d9f082f339133035dab0d

I‘m thankful for any clues what could be wrong. Am I doing something wrong with the claimpegin input parameter format?

Thanks in advance and kind regards.

**Comment by instagibbs** [comment]
That error in this case means the txoutproof doesn't match the transaction given(txids don't match). Fwiw I validated your proof posted and got this transaction id: https://blockstream.info/tx/cb4ddb6eb12f55ec5d1b9361ee92429a248f90c03edc8988e363e6ff9666518e

**Comment by instagibbs** [comment]
If you wouldn't mind posting the transaction you gave, since you already doxxed your txid :P

**Comment by philipp634** [comment]
So simple and I didn't catch it: it was a copy/paste error either with the the txid or the txoutproof (desperately trying to undoxx here ;)) from an earlier test run I made with a random transaction while waiting for the 102 blocks confirmation.

Thanks for your help!
